[2023-09-21T07:38:57.615+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.install_dbt_deps manual__2023-09-21T07:38:35.828621+00:00 [queued]>
[2023-09-21T07:38:57.631+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.install_dbt_deps manual__2023-09-21T07:38:35.828621+00:00 [queued]>
[2023-09-21T07:38:57.632+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T07:38:57.954+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): install_dbt_deps> on 2023-09-21 07:38:35.828621+00:00
[2023-09-21T07:38:57.963+0000] {standard_task_runner.py:57} INFO - Started process 129 to run task
[2023-09-21T07:38:57.971+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'install_dbt_deps', 'manual__2023-09-21T07:38:35.828621+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpy08od8j8']
[2023-09-21T07:38:57.975+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask install_dbt_deps
[2023-09-21T07:38:58.076+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.install_dbt_deps manual__2023-09-21T07:38:35.828621+00:00 [running]> on host 3e956870ddeb
[2023-09-21T07:38:58.211+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='install_dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T07:38:35.828621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T07:38:35.828621+00:00'
[2023-09-21T07:38:58.215+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-21T07:38:58.216+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt deps --profiles-dir /.dbt --project-dir /dbt_project']
[2023-09-21T07:38:58.248+0000] {subprocess.py:86} INFO - Output:
[2023-09-21T07:39:04.727+0000] {subprocess.py:93} INFO - [0m07:39:04  Running with dbt=1.5.3
[2023-09-21T07:39:04.733+0000] {subprocess.py:93} INFO - [0m07:39:04  Encountered an error:
[2023-09-21T07:39:04.733+0000] {subprocess.py:93} INFO - Runtime Error
[2023-09-21T07:39:04.734+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /dbt_project/dbt_project.yml
[2023-09-21T07:39:04.734+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-09-21T07:39:04.734+0000] {subprocess.py:93} INFO - 
[2023-09-21T07:39:07.150+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-21T07:39:07.167+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-21T07:39:07.172+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=main_dag, task_id=install_dbt_deps, execution_date=20230921T073835, start_date=20230921T073857, end_date=20230921T073907
[2023-09-21T07:39:07.204+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task install_dbt_deps (Bash command failed. The command returned a non-zero exit code 2.; 129)
[2023-09-21T07:39:07.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T07:39:07.288+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
