[2023-09-23T14:11:17.764+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tests_dag.test_db_conns manual__2023-09-23T14:11:09.855644+00:00 [queued]>
[2023-09-23T14:11:17.780+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tests_dag.test_db_conns manual__2023-09-23T14:11:09.855644+00:00 [queued]>
[2023-09-23T14:11:17.781+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-23T14:11:17.805+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): test_db_conns> on 2023-09-23 14:11:09.855644+00:00
[2023-09-23T14:11:17.811+0000] {standard_task_runner.py:57} INFO - Started process 1012 to run task
[2023-09-23T14:11:17.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tests_dag', 'test_db_conns', 'manual__2023-09-23T14:11:09.855644+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpq99r5n6y']
[2023-09-23T14:11:17.818+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask test_db_conns
[2023-09-23T14:11:17.892+0000] {task_command.py:415} INFO - Running <TaskInstance: tests_dag.test_db_conns manual__2023-09-23T14:11:09.855644+00:00 [running]> on host 4ef300bfa8d2
[2023-09-23T14:11:18.031+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tests_dag' AIRFLOW_CTX_TASK_ID='test_db_conns' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T14:11:09.855644+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T14:11:09.855644+00:00'
[2023-09-23T14:11:18.032+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-23T14:11:18.033+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pytest /opt/***/dags/dag_scripts/tests/test_db_connections.py']
[2023-09-23T14:11:18.048+0000] {subprocess.py:86} INFO - Output:
[2023-09-23T14:11:19.363+0000] {subprocess.py:93} INFO - ============================= test session starts ==============================
[2023-09-23T14:11:19.364+0000] {subprocess.py:93} INFO - platform linux -- Python 3.8.18, pytest-7.4.2, pluggy-1.3.0
[2023-09-23T14:11:19.364+0000] {subprocess.py:93} INFO - rootdir: /opt/***/dags/dag_scripts/tests
[2023-09-23T14:11:19.365+0000] {subprocess.py:93} INFO - plugins: anyio-4.0.0
[2023-09-23T14:11:19.365+0000] {subprocess.py:93} INFO - collected 7 items
[2023-09-23T14:11:19.365+0000] {subprocess.py:93} INFO - 
[2023-09-23T14:11:19.765+0000] {subprocess.py:93} INFO - ../../opt/***/dags/dag_scripts/tests/test_db_connections.py .......  [100%]
[2023-09-23T14:11:19.765+0000] {subprocess.py:93} INFO - 
[2023-09-23T14:11:19.766+0000] {subprocess.py:93} INFO - ============================== 7 passed in 1.06s ===============================
[2023-09-23T14:11:20.370+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-23T14:11:20.429+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=tests_dag, task_id=test_db_conns, execution_date=20230923T141109, start_date=20230923T141117, end_date=20230923T141120
[2023-09-23T14:11:20.481+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-23T14:11:20.547+0000] {taskinstance.py:2776} INFO - 4 downstream tasks scheduled from follow-on schedule check
