[2023-09-23T14:13:30.260+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tests_dag.test_db_conns manual__2023-09-23T14:13:22.443696+00:00 [queued]>
[2023-09-23T14:13:30.285+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tests_dag.test_db_conns manual__2023-09-23T14:13:22.443696+00:00 [queued]>
[2023-09-23T14:13:30.286+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-23T14:13:30.315+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): test_db_conns> on 2023-09-23 14:13:22.443696+00:00
[2023-09-23T14:13:30.321+0000] {standard_task_runner.py:57} INFO - Started process 1103 to run task
[2023-09-23T14:13:30.326+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tests_dag', 'test_db_conns', 'manual__2023-09-23T14:13:22.443696+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpb854xzdy']
[2023-09-23T14:13:30.332+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask test_db_conns
[2023-09-23T14:13:30.437+0000] {task_command.py:415} INFO - Running <TaskInstance: tests_dag.test_db_conns manual__2023-09-23T14:13:22.443696+00:00 [running]> on host 4ef300bfa8d2
[2023-09-23T14:13:30.608+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tests_dag' AIRFLOW_CTX_TASK_ID='test_db_conns' AIRFLOW_CTX_EXECUTION_DATE='2023-09-23T14:13:22.443696+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-23T14:13:22.443696+00:00'
[2023-09-23T14:13:30.613+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-23T14:13:30.615+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pytest /opt/***/dags/dag_scripts/tests/test_db_connections.py']
[2023-09-23T14:13:30.635+0000] {subprocess.py:86} INFO - Output:
[2023-09-23T14:13:31.729+0000] {subprocess.py:93} INFO - ============================= test session starts ==============================
[2023-09-23T14:13:31.729+0000] {subprocess.py:93} INFO - platform linux -- Python 3.8.18, pytest-7.4.2, pluggy-1.3.0
[2023-09-23T14:13:31.730+0000] {subprocess.py:93} INFO - rootdir: /opt/***/dags/dag_scripts/tests
[2023-09-23T14:13:31.730+0000] {subprocess.py:93} INFO - plugins: anyio-4.0.0
[2023-09-23T14:13:31.730+0000] {subprocess.py:93} INFO - collected 7 items
[2023-09-23T14:13:31.731+0000] {subprocess.py:93} INFO - 
[2023-09-23T14:13:31.985+0000] {subprocess.py:93} INFO - ../../opt/***/dags/dag_scripts/tests/test_db_connections.py .......  [100%]
[2023-09-23T14:13:31.986+0000] {subprocess.py:93} INFO - 
[2023-09-23T14:13:31.986+0000] {subprocess.py:93} INFO - ============================== 7 passed in 0.75s ===============================
[2023-09-23T14:13:32.602+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-09-23T14:13:32.657+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=tests_dag, task_id=test_db_conns, execution_date=20230923T141322, start_date=20230923T141330, end_date=20230923T141332
[2023-09-23T14:13:32.707+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-23T14:13:32.754+0000] {taskinstance.py:2776} INFO - 4 downstream tasks scheduled from follow-on schedule check
